# Generated by Django 2.1.5 on 2019-03-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ucook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
